modules:
  mimoto:
    enabled: true
    image:
      repository: mosipid/apitest-mimoto
      tag: 0.15.1
      pullPolicy: Always
  prereg:
    enabled: false
  masterdata:
    enabled: false
  idrepo:
    enabled: false
  partner:
    enabled: false
  pms:
    enabled: false
  resident:
    enabled: false
  auth:
    enabled: false
  esignet:
    enabled: false
