GetIssuerConfiguration:
   Mimoto_GetIssuerConfiguration_Mosip_All_Valid_Smoke:
      endPoint: /v1/mimoto/issuers/Mosip/configuration
      description: Retrieving verifiers list with all valid parameters
      uniqueIdentifier: TC_Mimoto_GetIssuerConfiguration_01
      role: resident
      restMethod: get
      checkErrorsOnlyInResponse: true
      inputTemplate: mimoto/GetIssuerConfiguration/GetIssuerConfiguration
      outputTemplate: mimoto/GetIssuerConfiguration/GetIssuerConfigurationResult
      input: '{
}'
      output: '{
}'
   Mimoto_GetIssuerConfiguration_With_Issuer_Removed_From_URL_Neg:
      endPoint: /v1/mimoto/issuers/configuration
      description: Retrieving verifiers list with invalid URL
      uniqueIdentifier: TC_Mimoto_GetIssuerConfiguration_02
      role: resident
      restMethod: get
      checkErrorsOnlyInResponse: true
      inputTemplate: mimoto/GetIssuerConfiguration/GetIssuerConfiguration
      outputTemplate: mimoto/error
      input: '{
}'
      output: '{
	"errors":[
		{
		"errorCode":"RESIDENT-APP-035"
		}
	]
}'